version: "3.9"

services:
  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:4.0
    restart: always
    ports:
      - "8181:8080"
    environment:
      # see https://github.com/mediagis/nominatim-docker/tree/master/4.0#configuration for more options
      PBF_URL: https://download.geofabrik.de/russia-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/russia-updates/
      NOMINATIM_PASSWORD: very_secure_password
    volumes:
      - nominatim_data:/var/lib/postgresql/12/main
    shm_size: 10gb

volumes:
  nominatim_data:
